name: Hourly tweet
on:
  schedule:
    - cron:  '12 * * * *'
jobs:
  daily_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'fxcoudert/PapersBot'
          path: 'PapersBot'
      - name: Check python version
        run: python3 -V
      - name: Display directory structure
        run: |
          ls -la
          ls -la PapersBot
      - name: Run PapersBot
        env:
          PYTHONUNBUFFERED: 1
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        run: python3 ./PapersBot/papersbot.py
      - name: Commit changes to posted list
        run: |
          git config --global user.name 'Hourly tweeting script'
          git config --global user.email 'fxcoudert@users.noreply.github.com'
          git commit posted.dat -m 'Papers were posted'
          git push
