name: Hourly tweet
on:
  schedule:
    - cron:  '55 * * * *'
jobs:
  daily_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'fxcoudert/PapersBot'
          path: 'PapersBot'
      - name: Configure git
        run: |
          git config --global user.name 'Daily update script'
          git config --global user.email 'fxcoudert@users.noreply.github.com'
      - name: Check python version
        env:
          PYTHONUNBUFFERED: 1
        run: python3 -V
      - name: Display directory structure
        run: |
          ls -la
          ls -la PapersBot
