name: Hourly tweet
on:
  push:
  schedule:
    - cron:  '05 * * * *'
jobs:
  daily_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'pzarabadip/PapersBot'
          path: 'PapersBot'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Check python version
        run: python -V
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install beautifulsoup4 feedparser tweepy pyyaml
      - name: Display directory structure
        run: |
          ls -la
          ls -la PapersBot
      - name: Run PapersBot
        env:
          PYTHONUNBUFFERED: 1
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        run: python ./PapersBot/papersbot.py
      - name: Commit changes to posted list
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Battery Papers"
	  git config --local pull.rebase false
	  git pull
          git diff --quiet --exit-code posted.dat || (git commit posted.dat -m 'Papers were posted' && git push)
